config/routes.rb
Flareteam::Application.routes.draw do

  resources :activations do
    resources :comments
  end
  resources :organization_invitation_requests

  resources :organizations

  devise_for :users,
    controllers: { sessions: 'sessions',
                   registrations: 'registrations',
                   invitations: 'users/invitations' }
  resource :profile

  root :to => 'activations#index'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user, inverse_of: :profile
  attr_accessible :user_id,
    :wants_email_notifications,
    :time_zone

  def time_zone
    super.presence || Rails.configuration.time_zone
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  respond_to :html

  def edit
    @user = current_user
    @profile = current_user.profile
    @organization = current_organization
  end

  def update
    @profile = current_user.profile

    if @profile.update_attributes(params[:profile])
      flash[:notice] = "Profile was successfully updated."
    end
    redirect_to edit_profile_path
  end
end

app/views/profiles/_form.html.haml
= simple_form_for(@profile) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :wants_email_notifications,
      label: "Email me with activation updates.",
      wrapper: :checkbox

  .form-actions
    = f.button :submit

app/views/profiles/edit.html.haml
.row
  .span3
    %ul.nav.nav-list.affix{data: {'client-behavior' => 'affix'}}
      %li.active
        %a{href: '#profile'}
          %i.icon-chevron-right
          Profile
      %li
        %a{href: '#settings'}
          %i.icon-chevron-right
          Settings

  .span8
    %section#profile
      .page-header
        %h1 Profile
      = simple_form_for(@user, url: registration_path(@user)) do |f|
        = f.error_notification
        %fieldset.form-horizontal
          .form-inputs
            = f.input :email, required: true, autofocus: true
            = f.input :password, :autocomplete => 'off', required: false
            = f.input :password_confirmation, required: false
            %hr
            = f.input :first_name
            = f.input :last_name
            = f.input :emergency_role, label: 'Role during emergencies'
            = f.input :mobile_phone_number
            = f.input :landline_phone_number
            = f.input :street_address
            = f.input :city
            = f.input :state
          .form-actions
            = f.button :submit, 'Update', class: 'btn btn-primary'

    %section#settings
      .page-head
        %h1 Settings
      = simple_form_for @profile do |f|
        = f.error_notification
        %fieldset.form-horizontal
          .form-inputs
            = f.input :wants_email_notifications,
              label: 'Email me with activation updates.', wrapper: :checkbox
            = f.input :time_zone
          .form-actions
            = f.button :submit, class: 'btn btn-primary'

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %tr
    %th User
    %th Wants email notifications
    %th
    %th
    %th

  - @profiles.each do |profile|
    %tr
      %td= profile.user_id
      %td= profile.wants_email_notifications
      %td= link_to 'Show', profile
      %td= link_to 'Edit', edit_profile_path(profile)
      %td= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path