config/routes.rb
Flareteam::Application.routes.draw do

  resources :activations do
    resources :comments
  end
  resources :organization_invitation_requests

  resources :organizations

  devise_for :users,
    controllers: { sessions: 'sessions',
                   registrations: 'registrations',
                   invitations: 'users/invitations' }
  resource :profile

  root :to => 'activations#index'
end

app/models/activation.rb
class Activation < ActiveRecord::Base
  belongs_to :organization, inverse_of: :activations
  has_many :comments, dependent: :destroy
  validate :title, :description, :location, :organization, presence: true

  attr_accessible :description, :location, :title
  default_scope order("created_at DESC")

  def to_s
    title
  end

  def subscribers
    organization.members.wanting_email_notifications
  end
end

app/controllers/activations_controller.rb
class ActivationsController < ApplicationController
  def index
    @activations = current_user.activations

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activations }
    end
  end

  def show
    @activation = current_user.activations.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activation }
    end
  end

  def new
    @activation = current_user.activations.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activation }
    end
  end

  # GET /activations/1/edit
  def edit
    @activation = current_user.activations.find(params[:id])
  end

  # POST /activations
  # POST /activations.json
  def create
    @activation = current_user.activations.build(params[:activation])

    respond_to do |format|
      if @activation.save
        format.html { redirect_to @activation, notice: 'Activation was successfully created.' }
        format.json { render json: @activation, status: :created, location: @activation }
      else
        format.html { render action: "new" }
        format.json { render json: @activation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @activation = current_user.activations.find(params[:id])

    respond_to do |format|
      if @activation.update_attributes(params[:activation])
        format.html { redirect_to @activation, notice: 'Activation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @activation = current_user.activations.find(params[:id])
    @activation.destroy

    respond_to do |format|
      format.html { redirect_to activations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/views/activations/_form.html.haml
= simple_form_for(@activation) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :location
    = f.input :description

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/activations/edit.html.haml
%h1 Editing activation

= render 'form'

= link_to 'Show', @activation
\|
= link_to 'Back', activations_path

app/views/activations/index.html.haml
.row
  .span12.page-header
    %h1.pull-left
      Activations

.row
  .span12
    .pull-right.actions
      = link_to "New Activation", new_activation_path, class: "btn btn-info"
    %ul.unstyled
      - @activations.each do |activation|
        .row
          .span6
            %li
              %h2
                = link_to activation.title, activation
              %p.muted #{l(activation.created_at)} in #{activation.location}
              %p= activation.description

app/views/activations/new.html.haml
%fieldset
  %legend New activation
  = render "form"

app/views/activations/show.html.haml
.row
  .span8.page-header
    %h1.pull-left
      = @activation.title
      %small
        = @activation.location
        = l(@activation.created_at)
  .span8
    .btn-group.pull-right
      = link_to "Invite people", new_user_invitation_path, class: "btn"
      %a.btn.dropdown-toggle{href: "#", data: {toggle: "dropdown"}}
        Actions
        %span.caret
      %ul.dropdown-menu
        %li
          = link_to "Edit", edit_activation_path(@activation)
        %li.divider
        %li
          = link_to "Delete Activation", @activation,
            method: :delete,
            data: { confirm: "Are you sure?" }
    .description.row
      .span6
        = simple_format(@activation.description, class: "lead")

.row
  .span6
    = simple_form_for [@activation, @comment] do |f|
      %legend Post an Update
      .form-inputs
        = f.input :title,
          label: false,
          input_html: { class: "input-xxlarge" },
          placeholder: "Title"
        = f.input :body,
          label: false,
          placeholder: "Message",
          input_html: { class: "input-xxlarge", rows: 5 }
        = f.input :attachment,
          label: false

      .form-actions
        = f.button :submit, "Post Update", class: "btn btn-primary pull-right"
    = render @activation.comments