config/routes.rb
Flareteam::Application.routes.draw do

  resources :activations do
    resources :comments
  end
  resources :organization_invitation_requests

  resources :organizations

  devise_for :users,
    controllers: { sessions: 'sessions',
                   registrations: 'registrations',
                   invitations: 'users/invitations' }
  resource :profile

  root :to => 'activations#index'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :members, class_name: 'User'
  has_many :activations, inverse_of: :organization
  has_many :organization_invitation_requests, dependent: :destroy

  attr_accessible :city, :zip_code, :emergency_role, :employee_count_range,
    :name, :phone, :primary_contact_email, :primary_contact_name,
    :primary_contact_phone, :state, :street_address

  validates :name, :primary_contact_name, :primary_contact_phone,
    :emergency_role, presence: true

  before_destroy :destroyable?

  def destroyable?
    members.empty? && activations.empty?
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = OrganizationDecorator.decorate_collection Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  def edit
    @user = User.new
    @organization = Organization.find(params[:id])
  end

  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= simple_form_for(@organization) do |f|
  = f.error_notification
  %fieldset.form-horizontal
    .form-inputs
      = f.input :name
      = f.input :street_address
      = f.input :city
      = f.input :state
      = f.input :zip_code
      = f.input :phone
      = f.input :primary_contact_name
      = f.input :primary_contact_phone
      = f.input :primary_contact_email
      = f.input :employee_count_range, 
        collection: ["1-10"], 
        label: "Number of employees"
      = f.input :emergency_role, 
        label: "Role during emergencies",
        input_html: { class: "input-xxlarge", rows: "8" }

    .form-actions
      = f.button :submit, class: 'btn btn-primary'

app/views/organizations/_organization.html.haml
%li.organization
  = organization.show_link
  = organization.destroy_link

app/views/organizations/edit.html.haml
.row
  .span3
    %ul.nav.nav-list.affix{data: {'client-behavior' => 'affix'}}
      %li.active
        %a{href: '#organization'}
          %i.icon-chevron-right
          Organization
      %li
        %a{href: '#invite'}
          %i.icon-chevron-right
          Invite
      %li
        %a{href: '#invitation-requests'}
          %i.icon-chevron-right
          Invitation requests
          - if @notifications > 0
            %span.badge.badge-success= @notifications

  .span8
    %section#organization
      .page-header
        %h1 Organization
        = render 'form'

    %section#invite
      .page-header
        %h1 Invite
        = simple_form_for(@user, as: :user, url: invitation_path(@user)) do |f|
          = f.error_notification
          %fieldset.form-horizontal
            .form-inputs
              = f.input :email
            .form-actions
              = f.button :submit, 'Invite', class: 'btn btn-primary'

    %section#invitation-requests
      .page-header
        %h1 Invitation requests
        - if @organization.organization_invitation_requests.any?
          You have #{@notifications} pending invitation #{'request'.pluralize(@notifications)}.
          %table.table
            %thead
              %tr
                %th Email
                %th
            %tbody
              = render @organization.organization_invitation_requests
        - else
          %p There are no pending invitation requests.

app/views/organizations/index.html.haml
%ul
  = render @organizations

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%fieldset
  %legend New organization
  = render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%p#notice= notice

.span8.page-header
  %h1= @organization.name
.span8
  .btn-group.pull-right
    = link_to 'Invite people', new_user_invitation_path, class: 'btn'
    = link_to 'Edit', edit_organization_path(@organization), class: 'btn'
  %p
    %b Street address:
    = @organization.street_address
  %p
    %b City:
    = @organization.city
  %p
    %b State:
    = @organization.state
  %p
    %b Phone:
    = @organization.phone
  %p
    %b Primary contact name:
    = @organization.primary_contact_name
  %p
    %b Primary contact phone:
    = @organization.primary_contact_phone
  %p
    %b Primary contact email:
    = @organization.primary_contact_email
  %p
    %b Emergency role:
    = @organization.emergency_role
  %p
    %b Employee count range:
    = @organization.employee_count_range